{% set name = "securesystemslib" %}
{% set version = "0.31.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/securesystemslib-{{ version }}.tar.gz
  sha256: c1594afbcd5db198ec90c487e1720154afb71743d9f4bccf3dfda84de650c478

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8

test:
  imports:
    - securesystemslib
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/secure-systems-lab/securesystemslib
  license: MIT AND CC0-1.0
  license_file:
    - LICENSE
    - securesystemslib/_vendor/ed25519/LICENSE
  summary: A library that provides cryptographic and general-purpose routines for Secure Systems Lab projects at NYU

extra:
  recipe-maintainers:
    - kenodegard
